### ISSUE TITLE
Error: No file or directory

### ISSUE THREAD

**Issue by qolina** [ljhgabe/BERT-ParsCit#2]
```
Traceback (most recent call last):
  File "/home/yanxia/anaconda3/envs/parscit/lib/python3.8/pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/data3/jiahe/logs/experiments/runs/default/2022-06-08_06-46-35'
```

How to customize the directories in the project? There are a lot.

**Comment by ljhgabe** [comment]
Hi Yanxia,
Please proceed to configs/datamodule, logger_dir and models etc to modify all the necessary cache directories to remove the error. The current setting with "/data3/jiahe" is based on my experiments on sle server. You can change it to your own target caching directories.

**Comment by qolina** [comment]
Maybe all absolute paths can be changed to relative paths? And we provide one default setting for users, all data stored into a cache directory under the project's home directory.

**Comment by ljhgabe** [comment]
Yes, that is also what the original template is using. I defined the configs this way so that I can train the model more easily from our server. I will change it back to the default settings

**Comment by qolina** [comment]
Ah, I see. thanks.
