### ISSUE TITLE
Do not know what file is downloaded

### ISSUE THREAD

**Issue by qolina** [ljhgabe/BERT-ParsCit#3]
```
Downloading: 100%|██████████████████████████████████████████████████████████████████████| 385/385 [00:00<00:00, 243kB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████| 223k/223k [00:01<00:00, 223kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████| 385/385 [00:00<00:00, 250kB/s]
```

**Comment by ljhgabe** [comment]
Hi Yanxia,

If you want to know what file is downloaded, you can set the debug=default through the command line. Alternatively I can also include some lines of code to print what data file is being downloaded. 

As for the second issue, I am not sure what you mean. Could you elaborate on that? The download and cache behaviour is specified by HuggingFace datasets so I am not sure what I can do about it.

**Comment by qolina** [comment]
Yes, please print a line to indicate which files are being downloaded.
